# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
# Фиксим права ДО использования Java/Gradle
    - name: Fix permissions
      run: |
        git update-index --chmod=+x gradlew
        chmod +x gradlew
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4.1.0
    - name: Build with Gradle Wrapper
      run: ./gradlew build
    - name: Clean with Gradle Wrapper
      run: ./gradlew clean

  dependency-submission:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

# Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
# See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

# ==============================================
# 3. Пуш в ОБЩИЙ репозиторий
# ==============================================
  push-to-repo:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Import GPG key and sign commit (✔️ Verified)
      if: success() && startsWith(github.event.head_commit.message, 'TASK')
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        GIT_COMMITTER_NAME: "Anna"
        GIT_COMMITTER_EMAIL: "12345678+svetlovaanna@users.noreply.github.com"
        TARGET_FOLDER: "core"
        AUTH_REPO_URL: https://${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/svetlovaanna/travel_test.git
      run: |
        set -e

        echo "$GPG_PRIVATE_KEY" | gpg --batch --import
        KEY_ID=$(gpg --list-secret-keys --keyid-format LONG | grep sec | awk '{print $2}' | cut -d'/' -f2)

        echo "use-agent" >> ~/.gnupg/gpg.conf
        echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
        echo RELOADAGENT | gpg-connect-agent

        git config --global user.name "Anna"
        git config --global user.email "191621076+svetlovaanna@users.noreply.github.com"
        git config --global commit.gpgsign true
        git config --global user.signingkey "0D978B848B18739D"
        git config --global gpg.program gpg

        git clone --filter=blob:none --sparse $AUTH_REPO_URL target-repo
        cd target-repo

        git sparse-checkout set $TARGET_FOLDER
        git checkout main || git checkout -b main

        rm -rf $TARGET_FOLDER
        cp -r ../$TARGET_FOLDER $TARGET_FOLDER

        git add $TARGET_FOLDER
        COMMIT_MSG="${{ github.event.head_commit.message || 'Signed sync from Anna' }}"
  
        GIT_COMMITTER_NAME="Anna" \
        GIT_COMMITTER_EMAIL="191621076+svetlovaanna@users.noreply.github.com" \
        git commit -m "$COMMIT_MSG" --gpg-sign="$KEY_ID" --author="Anna <191621076+svetlovaanna@users.noreply.github.com>" || echo "No changes"
  
        git push origin main

# ==============================================
# 5. Уведомления в Telegram
# ==============================================
  telegram-success:
    needs: [build, dependency-submission, push-to-repo]
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
    - name: Telegram Success
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: |
          ✅ *Сборка успешна* 
          Репозиторий: ${{ github.repository }}
          Коммит: [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})
          Логи: [Посмотреть](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          parse_mode: markdown

  telegram-failure:
    needs: [ build, dependency-submission, push-to-repo ]
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
    - name: Telegram Failure
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: |
          ❌ *Ошибка на одном из этапов*
          ${{
            needs.build.result == 'failure' && '*Упал этап:* `build`' ||
            needs.dependency-submission.result == 'failure' && '*Упал этап:* `dependency-submission`' ||
            needs.push-to-repo.result == 'failure' && '*Упал этап:* `push-to-repo`'
          }}
           Репозиторий: ${{ github.repository }}
           Коммит: [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})
           Логи: [Посмотреть](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
           parse_mode: markdown
